# Generated by Django 4.2.13 on 2024-06-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Agency'), (2, 'Applicant')], default=2),
        ),
    ]
