# Generated by Django 4.2.13 on 2024-07-28 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_report_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='summary',
            new_name='report',
        ),
    ]
