# Generated by Django 4.2.13 on 2024-08-04 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_rename_summary_case_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
