# Generated by Django 4.2.13 on 2024-08-04 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AddField(
            model_name='employee',
            name='agency',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__name': 'Agency'}, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
