# Generated by Django 4.2.13 on 2024-08-19 10:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_employee_fra"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="applicant_type",
            field=models.CharField(
                choices=[("household", "Household"), ("skilled", "Skilled")],
                default="household",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="consistency_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="employee",
            name="country",
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="created_date_of_report",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_deployment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="facebook",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="main_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("with_complain", "With Complain"),
                    ("arrive", "Arrive"),
                    ("no_communication", "No Communication"),
                    ("with_hearing", "With Hearing"),
                    ("blacklist", "Blacklist"),
                ],
                default="active",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
