# Generated by Django 4.2.13 on 2024-09-21 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_employeearrived_employeeblacklisted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Memory",
                "verbose_name_plural": "Employee Memories",
                "ordering": ["-created_at"],
            },
        ),
    ]
