# Generated by Django 4.2.13 on 2024-09-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeememory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
