# Generated by Django 4.2.13 on 2024-10-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_employee_is_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="token",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
