# Generated by Django 5.0.6 on 2024-07-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AICategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("role", models.CharField(max_length=500)),
                ("function_description", models.CharField(max_length=500)),
                (
                    "param_one_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "param_one_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "param_one_enum",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "param_two_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "param_two_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "param_two_enum",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "param_three_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "param_three_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "param_three_enum",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "param_four_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "param_four_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "param_four_enum",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
