# Generated by Django 5.0.6 on 2024-08-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("float", "Float"),
                            ("json", "JSON"),
                        ],
                        default="str",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
