# Generated by Django 4.2.13 on 2024-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advance", "0002_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicategory",
            name="closing_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aicategory",
            name="welcome_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
