
# Generated by Django 4.2.13 on 2025-10-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0003_aicategory_closing_message_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `advance_aicategory` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            "ALTER TABLE `advance_aicategory` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `advance_aicategory` MODIFY `welcome_message` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            "ALTER TABLE `advance_aicategory` MODIFY `welcome_message` longtext CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `advance_aicategory` MODIFY `closing_message` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            "ALTER TABLE `advance_aicategory` MODIFY `closing_message` longtext CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
    ]
