# Generated by Django 4.2.13 on 2024-09-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
