# Generated by Django 4.2.13 on 2024-09-27 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeememory'),
        ('chats', '0002_chat_is_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.employee'),
        ),
    ]
