# Generated by Django 4.2.13 on 2024-08-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fra", "0002_fra_agency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fra",
            options={"verbose_name": "FRA's", "verbose_name_plural": "FRA's"},
        ),
    ]
