# Generated by Django 4.2.13 on 2024-08-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement_of_facts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementoffacts',
            name='case',
        ),
    ]
