# Generated by Django 4.2.13 on 2024-08-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_of_facts', '0002_remove_statementoffacts_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementoffacts',
            name='emotion',
            field=models.CharField(default='neutral', max_length=50),
            preserve_default=False,
        ),
    ]
