# Generated by Django 4.2.13 on 2024-08-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_of_facts', '0003_statementoffacts_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementoffacts',
            name='ai_reference_link',
            field=models.URLField(blank=True, help_text='A URL for referencing this statement of facts.'),
        ),
        migrations.AddField(
            model_name='statementoffacts',
            name='consistency_analysis_included',
            field=models.BooleanField(default=False, help_text='Indicates whether consistency analysis was included in the statement.'),
        ),
    ]
