# Generated by Django 4.2.13 on 2024-09-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement_of_facts', '0005_statementoffacts_consistency_analysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementoffacts',
            options={'verbose_name': 'Statement of Facts', 'verbose_name_plural': 'Statements of Facts'},
        ),
    ]
