# Generated by Django 4.2.13 on 2024-10-13 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviewhub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementoffact",
            name="score",
            field=models.PositiveIntegerField(
                blank=True, help_text="Score between 1 and 100.", null=True
            ),
        ),
        migrations.AddField(
            model_name="statementoffact",
            name="suggestion",
            field=models.TextField(
                blank=True, help_text="Suggestions for improvement.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="statementoffact",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_statements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
