# Generated by Django 4.2.13 on 2024-06-23 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('employer', models.CharField(blank=True, max_length=255, null=True)),
                ('fra', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('contact1', models.CharField(blank=True, max_length=255, null=True)),
                ('contact2', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('relative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relative_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('relative_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('last_remarks', models.TextField(blank=True, null=True)),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('date_notify', models.DateField(blank=True, null=True)),
                ('chat_message_notify', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantRemarksHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('applicant_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_history', to='applicant.applicantcomplaint')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
